<a href="https://colab.research.google.com/github/siddhant-shekhar/rain_prediction/blob/main/ML1_assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing necessary libraries

In [192]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

from IPython.display import Image

# Importing the dataset weather.csv

In [120]:
data = pd.read_csv('/content/drive/MyDrive/Datasets/weather.csv')

In [121]:
data.head()

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0      8.0     24.3       0.0          3.4       6.3          NW   
1     14.0     26.9       3.6          4.4       9.7         ENE   
2     13.7     23.4       3.6          5.8       3.3          NW   
3     13.3     15.5      39.8          7.2       9.1          NW   
4      7.6     16.1       2.8          5.6      10.6         SSE   

   WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0           30.0         SW         NW           6.0  ...           29   
1           39.0          E          W           4.0  ...           36   
2           85.0          N        NNE           6.0  ...           69   
3           54.0        WNW          W          30.0  ...           56   
4           50.0        SSE        ESE          20.0  ...           49   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1019.7       1015.0         7         7     14.4     23.6         No   
1       1012.4       1008.4         5         3     17.5     25.7        Yes   
2       1009.5       1007.2         8         7     15.4     20.2        Yes   
3       1005.5       1007.0         2         7     13.5     14.1        Yes   
4       1018.3       1018.5         7         7     11.1     15.4        Yes   

   RISK_MM RainTomorrow  
0      3.6          Yes  
1      3.6          Yes  
2     39.8          Yes  
3      2.8          Yes  
4      0.0           No  

[5 rows x 22 columns]

In [122]:
data.columns.tolist()

['MinTemp',
 'MaxTemp',
 'Rainfall',
 'Evaporation',
 'Sunshine',
 'WindGustDir',
 'WindGustSpeed',
 'WindDir9am',
 'WindDir3pm',
 'WindSpeed9am',
 'WindSpeed3pm',
 'Humidity9am',
 'Humidity3pm',
 'Pressure9am',
 'Pressure3pm',
 'Cloud9am',
 'Cloud3pm',
 'Temp9am',
 'Temp3pm',
 'RainToday',
 'RISK_MM',
 'RainTomorrow']

# Checking the number of null values

In [123]:
data.isnull().sum()

MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          3
WindGustDir       3
WindGustSpeed     2
WindDir9am       31
WindDir3pm        1
WindSpeed9am      7
WindSpeed3pm      0
Humidity9am       0
Humidity3pm       0
Pressure9am       0
Pressure3pm       0
Cloud9am          0
Cloud3pm          0
Temp9am           0
Temp3pm           0
RainToday         0
RISK_MM           0
RainTomorrow      0
dtype: int64

# Droping the null rows and columns

In [124]:
data = data.dropna()

In [125]:
data.isnull().sum()

MinTemp          0
MaxTemp          0
Rainfall         0
Evaporation      0
Sunshine         0
WindGustDir      0
WindGustSpeed    0
WindDir9am       0
WindDir3pm       0
WindSpeed9am     0
WindSpeed3pm     0
Humidity9am      0
Humidity3pm      0
Pressure9am      0
Pressure3pm      0
Cloud9am         0
Cloud3pm         0
Temp9am          0
Temp3pm          0
RainToday        0
RISK_MM          0
RainTomorrow     0
dtype: int64

In [126]:
data.describe()

MinTemp     MaxTemp    Rainfall  Evaporation    Sunshine  \
count  328.000000  328.000000  328.000000   328.000000  328.000000   
mean     7.742988   20.897561    1.440854     4.702439    8.014939   
std      5.945199    6.707310    4.289427     2.681183    3.506646   
min     -5.300000    7.600000    0.000000     0.200000    0.000000   
25%      2.850000   15.500000    0.000000     2.550000    6.000000   
50%      7.900000   20.400000    0.000000     4.400000    8.750000   
75%     12.800000   25.800000    0.200000     6.600000   10.700000   
max     20.900000   35.800000   39.800000    13.800000   13.600000   

       WindGustSpeed  WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  \
count     328.000000    328.000000    328.000000   328.000000   328.000000   
mean       40.396341     10.414634     18.185976    71.100610    44.003049   
std        13.132176      7.811544      8.926759    12.983367    16.605975   
min        13.000000      2.000000      4.000000    36.000000    13.000000   
25%        31.000000      6.000000     11.000000    63.000000    32.000000   
50%        39.000000      7.000000     17.000000    71.000000    42.500000   
75%        46.000000     13.000000     24.000000    80.000000    54.000000   
max        98.000000     41.000000     52.000000    99.000000    93.000000   

       Pressure9am  Pressure3pm    Cloud9am    Cloud3pm     Temp9am  \
count   328.000000   328.000000  328.000000  328.000000  328.000000   
mean   1019.350000  1016.530793    3.905488    4.000000   12.815549   
std       6.715244     6.469774    2.974957    2.652101    5.542521   
min     996.500000   996.800000    0.000000    0.000000    0.100000   
25%    1014.800000  1012.400000    1.000000    1.000000    8.175000   
50%    1019.750000  1016.900000    4.000000    4.000000   13.500000   
75%    1024.300000  1021.125000    7.000000    7.000000   17.200000   
max    1035.700000  1033.200000    8.000000    8.000000   24.700000   

          Temp3pm     RISK_MM  
count  328.000000  328.000000  
mean    19.556402    1.422561  
std      6.644311    4.234023  
min      5.100000    0.000000  
25%     14.500000    0.000000  
50%     18.850000    0.000000  
75%     24.225000    0.200000  
max     34.500000   39.800000

In [127]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 328 entries, 0 to 365
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   MinTemp        328 non-null    float64
 1   MaxTemp        328 non-null    float64
 2   Rainfall       328 non-null    float64
 3   Evaporation    328 non-null    float64
 4   Sunshine       328 non-null    float64
 5   WindGustDir    328 non-null    object 
 6   WindGustSpeed  328 non-null    float64
 7   WindDir9am     328 non-null    object 
 8   WindDir3pm     328 non-null    object 
 9   WindSpeed9am   328 non-null    float64
 10  WindSpeed3pm   328 non-null    int64  
 11  Humidity9am    328 non-null    int64  
 12  Humidity3pm    328 non-null    int64  
 13  Pressure9am    328 non-null    float64
 14  Pressure3pm    328 non-null    float64
 15  Cloud9am       328 non-null    int64  
 16  Cloud3pm       328 non-null    int64  
 17  Temp9am        328 non-null    float64
 18  Temp3pm   

In [128]:
data.shape

(328, 22)

# Dividing the features and the target data

In [129]:
X = data.drop(columns = 'RainTomorrow', axis = 1)
y = data['RainTomorrow']

# Applying label encoder for all the string attributes

In [130]:
data['WindGustDir'].unique()

array(['NW', 'ENE', 'SSE', 'SE', 'E', 'S', 'N', 'WNW', 'ESE', 'NE', 'NNE',
       'NNW', 'SW', 'W', 'WSW', 'SSW'], dtype=object)

In [131]:
data['WindDir9am'].unique()

array(['SW', 'E', 'N', 'WNW', 'SSE', 'SE', 'S', 'WSW', 'NNE', 'NNW',
       'ENE', 'SSW', 'NW', 'ESE', 'NE', 'W'], dtype=object)

In [132]:
data['WindDir3pm'].unique()

array(['NW', 'W', 'NNE', 'ESE', 'E', 'ENE', 'WSW', 'NE', 'NNW', 'SE', 'S',
       'SW', 'WNW', 'N', 'SSW', 'SSE'], dtype=object)

In [133]:
Image(url = 'https://www.researchgate.net/profile/Curtis-Humphrey-2/publication/221473202/figure/fig5/AS:667773822849043@1536221094822/The-Sixteen-Point-Compass-as-presented-to-the-participants.ppm',  width=400, height=400)

In [134]:
from sklearn.preprocessing import LabelEncoder

In [135]:
le = LabelEncoder()

In [136]:
a= X.select_dtypes(include= ['object']).columns.tolist()
print(a)
len(X.select_dtypes(include= ['object']).columns.tolist())

['WindGustDir', 'WindDir9am', 'WindDir3pm', 'RainToday']


4

In [137]:
# so we have 4 columns with the data type object i.e. string.. so we will be encoding these five columns
# it can be done by two ways:
# first - by encoding individually i.e.=> data.WindGustDir = le.fit_transform(data.WindGustDir)
# second - all at once i.e. => data[data.select_dtypes(include= ['object']).columns] = data[data.select_dtypes(include= ['object']).columns].apply(le.fit_transform)
# I will go with second method

# “WindGustDir, WindDir”, Converting the above attributes into numbers

In [138]:
X[X.select_dtypes(include= ['object']).columns] = X[X.select_dtypes(include= ['object']).columns].apply(le.fit_transform)

In [139]:
X.head()

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustDir  \
0      8.0     24.3       0.0          3.4       6.3            7   
1     14.0     26.9       3.6          4.4       9.7            1   
2     13.7     23.4       3.6          5.8       3.3            7   
3     13.3     15.5      39.8          7.2       9.1            7   
4      7.6     16.1       2.8          5.6      10.6           10   

   WindGustSpeed  WindDir9am  WindDir3pm  WindSpeed9am  ...  Humidity9am  \
0           30.0          12           7           6.0  ...           68   
1           39.0           0          13           4.0  ...           80   
2           85.0           3           5           6.0  ...           82   
3           54.0          14          13          30.0  ...           62   
4           50.0          10           2          20.0  ...           68   

   Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0           29       1019.7       1015.0         7         7     14.4   
1           36       1012.4       1008.4         5         3     17.5   
2           69       1009.5       1007.2         8         7     15.4   
3           56       1005.5       1007.0         2         7     13.5   
4           49       1018.3       1018.5         7         7     11.1   

   Temp3pm  RainToday  RISK_MM  
0     23.6          0      3.6  
1     25.7          1      3.6  
2     20.2          1     39.8  
3     14.1          1      2.8  
4     15.4          1      0.0  

[5 rows x 21 columns]

In [154]:
y = le.fit_transform(y)

In [157]:
y

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [140]:
# now all the columsn have been encoded to the numerical value

# Applying MinMax Scaler

In [141]:
from sklearn.preprocessing import MinMaxScaler

In [142]:
minmax = MinMaxScaler()

In [143]:
scaled_data = minmax.fit_transform(X)

In [145]:
scaled_data

array([[0.50763359, 0.59219858, 0.        , ..., 0.6292517 , 0.        ,
        0.09045226],
       [0.73664122, 0.68439716, 0.09045226, ..., 0.70068027, 1.        ,
        0.09045226],
       [0.72519084, 0.56028369, 0.09045226, ..., 0.51360544, 1.        ,
        1.        ],
       ...,
       [0.67938931, 0.43617021, 0.        , ..., 0.44897959, 0.        ,
        0.        ],
       [0.67938931, 0.68439716, 0.        , ..., 0.70748299, 0.        ,
        0.        ],
       [0.67175573, 0.80141844, 0.        , ..., 0.79931973, 0.        ,
        0.        ]])

# Constructing Linear Regression Model

In [146]:
lin_reg = LinearRegression()

In [148]:
# train test split

In [174]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=3)

In [175]:
lin_reg.fit(X_train, y_train)

LinearRegression()

In [176]:
y_predict = lin_reg.predict(X_test)

In [177]:
lin_reg_mse = mean_squared_error(y_predict, y_test)

In [178]:
print(lin_reg_mse)

0.052018262848166394


# Finding r2 value

In [183]:
r2_initial = r2_score(y_test, y_predict)

In [184]:
print("r2 value is : ", r2_initial)

r2 value is :  0.5116561358478171


# Applying 6 Fold Cross Validation

In [186]:
cv = KFold(n_splits=6, shuffle=True, random_state=3)

In [187]:
cv_score = cross_val_score(lin_reg, X, y, cv = cv, scoring='r2')

# Finding r2 score again

In [189]:
cv_score # it is the r2 score of the 6 fold cross validation

array([0.5685007 , 0.48208465, 0.56450683, 0.50681711, 0.48563371,
       0.26919298])

In [193]:
np.mean(cv_score)

0.47945599511923925